### ISSUE TITLE
IEnumerable<primitive> is not working

### ISSUE THREAD

**Issue by christopheblin** [swagger-api/swagger-ui#1004]
Please see https://github.com/domaindrivendev/Swashbuckle/issues/211

To summarize, in swagger-ui, for the model I have
```javascript
"tokens": [
    "string"
  ],
"apps": [
    {
      "id": "string",
      "name": "string",
      "url": "string"
    }
  ]
```

So far so good but now when I click on the Model, I have 
```
tokens(string, optional)  //here is problematic
apps(Array[Application], optional) //here is ok
```
whereas I should have
```
tokens(Array[string], optional)  
apps(Array[Application], optional)
```

**Comment by webron** [comment]
@christopheblin - can you share the actual model you get in your swagger specification? what you're sharing here is not a valid model definition.

**Comment by christopheblin** [comment]
@webron I am at home at the moment and this is a bug I encounter at work with c#.

At the moment, there is a critical bug when you click on the Model link
http://petstore.swagger.io/#!/pet/findPetsByStatus

<hen you click on Model you only have array {} which is worse than having the problem I describe.

When this will be corrected like in the previous version, you could see that photoUrls is written as photoUrls(string, optionnal) instead of photoUrls(Array[string], optional)

hope that helps you to see the problem

**Comment by webron** [comment]
Sure. We're aware of the other issue you raised, so let's keep track on that.

**Comment by christopheblin** [comment]
@webron you mean #975 ?

**Comment by webron** [comment]
Yup, that's the one.

**Comment by christopheblin** [comment]
ok thanks I'll watch both bugs :)

**Comment by webron** [comment]
@christopheblin - I believe the issue is resolved now. Can you please retest?

**Comment by christopheblin** [comment]
sorry, I've been very busy these days and I have still not upgraded to latest version.
I will try to do that in the next few days...

**Comment by fehguy** [comment]
@christopheblin please reopen if you see an issue still.
