### ISSUE TITLE
Model Schema not showing number's without default or with default value of 0

### ISSUE THREAD

**Issue by tlbdk** [swagger-api/swagger-ui#1136]
![image](https://cloud.githubusercontent.com/assets/11635/7069459/30ba7d80-ded9-11e4-9929-c7373698646a.png)

![image](https://cloud.githubusercontent.com/assets/11635/7069489/61c5e298-ded9-11e4-898d-a77e453427f7.png)

```js
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Test sample showing swagger error",
        "description": "Show that response headers are not rendered",
        "contact": {
            "name": "Troels Liebe Bentsen",
            "email": "tlb@nversion.dk"
        }
    },
    "host": "localhost",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "post": {
                "summary": "Test",
                "description": "Test stuff",
                "operationId": "doTest",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        }                       
                    },
                    {
                        "in": "header",
                        "name": "ETag",
                        "description": "Used as caching key for future requests",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test stuff response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        },
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        }
                    }
                },
                "tags": ["test"]
            }
        }
    },
    "definitions": {
        "test": {
            "required": [
                "test1",
                "test2"
            ],
            "properties": {
                "test1": {
                    "type": "string"
                },
               "test": {
                    "description": "Amount to be payment",
                    "type": "number",
                    "format": "double",
                    "default": 0
                }
            }
        }
    }
}
```

**Comment by webron** [comment]
@whitlockjc - is this an issue with swagger-js?

**Comment by mohsen1** [comment]
Yes, swagger-js renders the Model Schema

**Comment by tlbdk** [comment]
Sorry i made a typo in the title

**Comment by fehguy** [comment]
please pull from develop_2.0 and retest.  I've verified that this should be working:

![image](https://cloud.githubusercontent.com/assets/249413/7101699/705dc9e6-e01a-11e4-80c2-c23596f8b6da.png)

**Comment by nostah** [comment]
I've just tried this on develop_2.0 (727812a5441bc9b7202680ad37b6b2e54b00dd8e) and it still does not work.

**Comment by fehguy** [comment]
did you run `npm i` before building develop_2.0?

**Comment by nostah** [comment]
no, I just used version from ./dist

**Comment by nostah** [comment]
ok, I've now rebuilt everything and it works fine. sorry for mess.

**Comment by fehguy** [comment]
Great, thank you

**Comment by tlbdk** [comment]
Fixed in newest stable, thanks :)
