### ISSUE TITLE
Latest swagger-ui shows all 1.2 model properties as Optional

### ISSUE THREAD

**Issue by ikitommi** [swagger-api/swagger-ui#1152]
- ui: http://petstore.swagger.io/
- spec: http://petstore.swagger.io/api/api-docs
- api: #!/pet/findPetsByTags

**Comment by webron** [comment]
Right, `Pet` should have `id` and `name` marked as required. I believe this is an issue with swagger-js. @whitlockjc?

**Comment by dariusz** [comment]
Thanks for noticing and resolving this!  Showstopper for my demo to the bosses.
+1

**Comment by fehguy** [comment]
I hope to have this worked out tonight along with a point release in npmjs.org

**Comment by webron** [comment]
@dariusz - no reason for it to be a showstopper. Since this issue is for 1.2 specs, you can just used an older stable version and present it. Check out the table - https://github.com/swagger-api/swagger-ui#compatibility - to see which version provides support for 1.2 (fine, I'll tell, it's 2.0.24).

**Comment by dariusz** [comment]
Ah awesome, thanks @webron. For anyone else new to git tags:

    git clone https://github.com/swagger-api/swagger-ui.git && cd swagger-ui
    git checkout tags/v2.0.24

**Comment by fehguy** [comment]
verified fixed in develop_2.0

**Comment by prat0318** [comment]
Is the fix merged to master? I pulled from master today and i am still facing the issue.

**Comment by webron** [comment]
This is not fixed.

**Comment by ponelat** [comment]
It broke, because of a change in behaviour, there are two ways to look for required props. Either on the property itself, or in the 'required' array in the containing schema. 

The line in question...
https://github.com/swagger-api/swagger-js/commit/7e8f9f805bb733b7cd1bf783ca8589c9a61686c8#diff-50e1922b706c52965ccc307155b8f407R245

I'm going to fix, by including **both** (required will be on the property and in the array), please advise if one or the other is preferred? Also note, this issue is with spec-converter (1.2)

**Comment by webron** [comment]
@ponelat - required *properties* are described using the `required` property with an array of required properties as the top of the model definition. *Parameters* on the other hand have a `required` property inside their definition which is boolean. Perhaps this is the source of confusion.

**Comment by webron** [comment]
Also, this behavior was the same in 1.2.

**Comment by ponelat** [comment]
@webron ok, so what I did previously was add the `required` boolean flag to model properties when converting 1.2 -> 2.0. This worked in the ui, as I made allowance for it. Since then, @fehguy corrected the logic in the templates (using the `required` array) which broke, as we weren't carrying across the `required` array when converting.
I've removed my erroneous logic and added the necessary conversion. This is all in swagger-js, swagger-ui is fine.

**Comment by ponelat** [comment]
@dwalden its fixed, and will most likely be in the next release.

**Comment by dwalden** [comment]
Thank you, much appreciated. It doesn't appear to have found its way into swagger-ui's master yet, I guess I will wait for that.

**Comment by webron** [comment]
@dwalden - it hasn't been merged into the develop branch yet, so definitely not in master.

If you're feeling adventurous and want to test @ponelat's fix, you can always clone his fork (https://github.com/ponelat/swagger-js/tree/fix/1152-required-properties) and run it.

**Comment by webron** [comment]
Done in develop_2.0.

**Comment by alexvodovoz** [comment]
@webron I'm still seeing the same issue in develop_2.0 and master.  Is this not how you describe a required definition property?
"properties": {
        "id": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "required": true
        }
}

**Comment by webron** [comment]
@alexagranov - no, it isn't. Below is an example of how a Pet is defined (from the pet store sample) in 1.2. You can see there's a separate `required` field which is an array of the field names.

```json
{
  "id": "Pet",
  "required": [
    "id",
    "name"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "unique identifier for the pet",
      "minimum": "0.0",
      "maximum": "100.0"
    },
    "category": {
      "$ref": "Category"
    },
    "name": {
      "type": "string"
    },
    "photoUrls": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "Tag"
      }
    },
    "status": {
      "type": "string",
      "description": "pet status in the store",
      "enum": [
        "available",
        "pending",
        "sold"
      ]
    }
  }
}
```
