### ISSUE TITLE
Array parameter contents displayed as "undefined"

### ISSUE THREAD

**Issue by Hephistocles** [swagger-api/swagger-ui#1613]
I'm afraid I can't tell if this is a problem with swagger UI or swagger JS, but here's the problem. When I include an array containing objects as one of my parameters, with the object schema inline, swagger UI displays the parameter type as "Array[undefined]". If I use $ref instead it works correctly. There's what looks like a similar problem with the swagger editor, so perhaps this is a problem from upstream. Minimal sample:

```
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      parameters:
        - name: "test"
          in: body
          schema:
            type: array
            items: 
              type: object
              properties:
                foo: 
                  type: string
                  example: "foo"
      responses:
        '200':
          description: OK
```

**Comment by julienboulay** [comment]
Same issue with Swagger-tools 0.9.14 which use swagger-ui v2.1.3.
Array parameter contents displayed as "undefined", even if a title is set within the inline "items" schema.

**Comment by julienboulay** [comment]
The bug was in the swagger-client Resolver object. Inline schema were not resolved in swagger-ui v2.1.3 version.
It is fixed in swagger-ui v2.1.4.
I've created a fork to update swagger-tools with swagger-ui v2.1.4.
It can be found here : https://github.com/julienboulay/swagger-tools

@webron : I think you can close this bug.

**Comment by webron** [comment]
@bodnia - can you please validate this is fixed?

**Comment by bodnia** [comment]
@webron this is fixed in latest master

![screen shot 2016-02-08 at 11 07 38 am](https://cloud.githubusercontent.com/assets/8950657/12881672/3a4a71aa-ce54-11e5-9db2-5e310bf8c57b.png)

**Comment by yuxiaomin** [comment]
@webron 
on http://petstore.swagger.io/ if I use my own API spec https://dl.dropboxusercontent.com/u/112488778/tropos/test.json
whose response has an array of object. But in UI I still see array[undefined]
![image](https://cloud.githubusercontent.com/assets/2513729/15198145/32976694-179b-11e6-851d-62eb2684d3db.png)
the swagger-ui used in swagger.io is already 2.1.4 I think .

**Comment by matteo-mosca** [comment]
I am still having the same bug as of SwaggerUI 2.2.6

![image](https://cloud.githubusercontent.com/assets/11195767/20479987/c7c8c2e8-afe0-11e6-93bd-0eaaf6ffd2fa.png)

Shall I open a new issue?

**Comment by fehguy** [comment]
@matteo-mosca yes, and please provide some details from your specification.

**Comment by matteo-mosca** [comment]
Thank you, opened #2510
