### ISSUE TITLE
$ref'd schema not working from within referenced parameter

### ISSUE THREAD

**Issue by perplexa** [swagger-api/swagger-ui#1674]
Hi,

I ran into a problem, where I am referencing parameters and one of the parameters has its own referenced schema.

Instead of showing the correct model definition, swagger-ui shows a link to the referenced item, e.g. `http://localhost:9000/v1/api-docs#/definitions/AmountPayload`.

For now, I am just using the schema directly in the parameter, but it would be cool if in future i can reference models there, too.

``` json
{
    "basePath": "/v1",
    "definitions": {
        "AmountPayload": {
            "properties": {
                "amount": {
                    "type": "integer"
                }
            },
            "type": "object"
        }
    },
    "host": "http://localhost:9000",
    "info": {
        "description": "some description",
        "title": "some api",
        "version": "1.1"
    },
    "parameters": {
        "amount": {
            "description": "The relative amount to update, can be either positive or negative.",
            "in": "body",
            "name": "amount",
            "required": true,
            "schema": {
                "$ref": "#/definitions/AmountPayload"
            }
        }
    },
    "paths": {
        "/products/somestuff": {
            "post": {
                "description": "desc",
                "parameters": [
                    {
                        "$ref": "#/parameters/amount"
                    }
                ],
                "summary": "hi",
                "tags": [
                    "Products"
                ]
            }
        }
    },
    "produces": [
        "application/json"
    ],
    "schemes": [
        "http",
        "https"
    ],
    "swagger": "2.0"
}
```

This is how it looks like in swagger-ui 2.1.2:

![swagger-ui](http://i.imgur.com/yiEvXaZ.png)

Bests
Daniel

**Comment by fehguy** [comment]
This should be fixed in master on swagger-ui, which will be released shortly.  Can you please try that and report back?

**Comment by perplexa** [comment]
I just tested on the current master (51ee684caa92c184cb6fcda0de894a4d814e58b1) and the issue still exists.

**Comment by jer-k** [comment]
I just tested on master (https://github.com/swagger-api/swagger-ui/commit/d59e4141a1157ea46896b838e1bf6dafd78428b1) and I'm seeing the same result. 

![screen shot 2015-11-18 at 4 25 23 pm](https://cloud.githubusercontent.com/assets/1280586/11258800/468f8a64-8e11-11e5-90c8-c639639d8324.png)

I'm trying to use `$ref` to pull in different files, but when trying to use `$ref` inside of a file that is being pulled in with `$ref` I see the above message.

*api.swagger.yaml*
```yaml
swagger: '2.0'
info:
  title: API
  version: 1.0.0
host: localhost:3000
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  "/api/vehicles/{vehicle_id}/trade_reports":
    parameters:
      - name: vehicle_id
        in: path
        required: true
        type: string
      - name: tc-session-token
        in: header
        required: true
        type: string
    post:
      tags: ["TradeReport"]
      parameters:
        - name: trade_report
          in: body
          required: true
          schema:
            $ref: "./schema/trade-report.yaml"
      responses:
        201:
          description: Created Trade Report
        403:
          description: Invalid session
        422:
          description: Could not create Trade Report
          schema:
            $ref: "#/definitions/Error"

  "/payments/calculate":
     $ref: './calculate.yaml'


definitions:
  ErrorModel:
    type: object
    properties:
      message:
        type: string
        description: Error message
```

*caculate.yaml*
```yaml
post:
  summary: Calculate Payments
  parameters:
    - name: trade_report
      in: body
      required: true
      schema:
        $ref: "./schema/trade-report.yaml"
  tags:
    - Payments
  responses:
    '200':
      schema:
        type: array
        items:
          type: integer
```

*/schema/trade-report.yaml*
```yaml
properties:
  vehicle:
    $ref: "#/definitions/Vehicle"
  condition:
    $ref: "#/definitions/Condition"

definitions:
  Vehicle:
    description: Still deciding on what these should be
    properties:
      vin:
        type: string
      complete:
        type: boolean
      version:
        type: integer
      trim_id:
        type: integer
      tbd:
        type: boolean

  Condition:
    description: Still deciding what these should be
    properties:
      tbd:
        type: boolean
```

**Comment by keanerickson** [comment]
Are schema meant to be usable as parameters? Doing so results in a blank parameter list in swagger-ui for me, with just "undefined" under the datatype. The Stuff schema used below works fine in other response bodies, as well.

		"save": {
			"post": {
				"tags": [
					"stuff"
				],
				"summary": "Save stuff",
				"description": "Save stuff",
				"produces": [
					"application/json"
				],
				"parameters": [
					{ "$ref": "#/definitions/Stuff" }
				],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "response.json#/definitions/SuccessResponse"
						}
					}
				}
			}
		}

**Comment by webron** [comment]
@keanerickson no. Parameters can be reusable, but they can't point to `definitions`, they have their own place in the spec. Parameters contain other metadata on top of the schema (like, their location and name) so it doesn't really make sense.
