### ISSUE TITLE
Recursive definition references not working

### ISSUE THREAD

**Issue by islemus** [swagger-api/swagger-ui#1679]
Hi guys,

I'm hosting both swagger-editor and swagger-ui. 
http://vm-linuxapp-75:8080/swagger/#/ for the swagger-editor and 
http://vm-linuxapp-75:8080/swagger-ui/ for swagger-ui

I have the spec file below hosted at http://vm-linuxapp-75:8080/swagger/specs/occupation.json (inside the swagger-editor). The file references definitions located in http://vm-linuxapp-75:8080/swagger/definitions/occupations.json using an absolute url. This latter definition references  another definition located in in http://vm-linuxapp-75:8080/swagger/definitions/map.json

Everything works fine in swagger-editor (the preview panel display all the definitions referenced). However, in swagger-ui when i try to load http://vm-linuxapp-75:8080/swagger/specs/occupation.json    only the first level of definitions are loaded, the definitions referenced by these last ones are not loaded

Here is an example 

``` json

// spec file
{
    "swagger": "2.0",
    "info": {
        "title": "Occupations API",
        "description": "This API manages Occupations",
        "version": "1.0.0"
    },
    "host": "localhost:8080",
    "schemes": [
        "http",
        "https"
    ],
    "basePath": "/",
    "produces": [
        "application/json",
        "application/xml"
    ],
    "paths": {
        "/occupations": {
            "post": {
                "tags": [
                    "Occupations"
                ],
                "summary": "Adds a new Occupation",
                "description": "",
                "consumes": [
                    "application/json",
                    "application/xml"
                ],
                "produces": [
                    "application/json",
                    "application/xml"
                ],
                "parameters": [
                    {
                        "name": "occupation",
                        "in": "body",
                        "description": "Occupatione object that needs to be added",
                        "required": true,
                        "schema": {
                            "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/occupation.json"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "M00-01 - If the record was created",
                        "schema": {
                            "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/error.json"
                        }
                    },
                    "500": {
                        "description": "M00-06 - Other cases",
                        "schema": {
                            "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/error.json"
                        }
                    }
                }
            }
        }
    }
}
```

``` json
occupation.json
{
    "properties": {
        "id": {
            "type": "string",
            "description": "Unique identifier representing a specific occupation"
        },
        "descriptions": {
            "type": "object",
            "description": "Description of the occupation",
            "properties": {
                "map": {
                    "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/map.json"
                }
            }
        }
    }
}
```

map.json

``` json

{
    "description": "A set of key-value pairs, one key per language",
    "properties": {
        "en": {
            "type": "string"
        },
        "fr": {
            "type": "string"
        }
    }
}
```

The map part is not loaded by swagger ui

![capture](https://cloud.githubusercontent.com/assets/12645698/10548554/a368d30c-7409-11e5-9987-80daa90f5b8d.PNG)

**Comment by bharrison1984** [comment]
I noticed the same thing and was going to post an issue. Looks like you beat me to it.

**Comment by DerManoMann** [comment]
Same here. It might be that the required lists are not merged, because if a property is not required the behaviour is the same even without nesting.

**Comment by rex** [comment]
I am experiencing the same issue. I just realized this is the `swagger-ui` repo and not the `swagger-editor` repo, but it seems relevant to both so I'm commenting here for exposure/cross-pollination purposes. 

![screenshot 2016-07-14 15 57 00 redacted](https://cloud.githubusercontent.com/assets/4247754/16855990/7b33f5a6-49dd-11e6-9538-8f3582925962.png)

**Comment by lxjuly** [comment]
@rex I have an object has a circular reference of itself. That's the whole point doing this. But it seems swagger editor does not support it

**Comment by rex** [comment]
@lxjuly Indeed. Which is understandable, though I wish it were supported because it seems a common use case.

**Comment by fehguy** [comment]
Recursive definitions -are- supported but the examples will be truncated. What do you see with current master that is wrong?

**Comment by rex** [comment]
Hi @fehguy! There's a solid chance that I may have been doing it wrong, but I posted above with a screenshot of what I was seeing on my end. The circular reference is: 

A `Bay` can contain a `Reservation`, and populates it if criteria are met. A `Reservation` contains a reference to the `Bay`, which is always populated. So in attempting to document a response for a `Bay` endpoint I was seeing something like the following:

```javascript
// GET /bays/1
{
  "bay": {
    "id": 1,
    "foo": "bar",
    "reservation_id": 1,
    "reservation": {
      "id": 1,
      "foo": "bar",
      "bay": {
        "id": 1
        // NOTE: No Reservation population in pre-decorated record
      }
    }
  }
}
```

But when documenting it with swagger-editor as soon as I added the `Bay` reference to the `Reservation` schema it caused all references to show as `undefined` in the UI. Removing the `Bay` reference from the `Reservation` schema instantly re-populated all references in the UI.

If there is a way that I can achieve this without breaking things, I'd appreciate some guidance! Also, if posting the actual schema here (redacted, of course) will help, please let me know.

Thank you!

**Comment by webron** [comment]
@rex - there *is* an issue with swagger-editor, but this is swagger-ui we're talking about. Do you experience issues with swagger-ui?

**Comment by lxjuly** [comment]
@webron This is a swagger-ui problem not the editor

**Comment by rex** [comment]
@webron I was seeing this behavior while using swagger-editor. I posted here because it was relevant in context and I assumed that the two were at least somewhat related (though that could easily be an incorrect assumption).

**Comment by webron** [comment]
Okay, so I'm confused. Some say the issue is with swagger-ui, and some with swagger-editor. The two projects are completely independent and share pretty much nothing right now. So if the issue is with swagger-editor, it should be opened there.

**Comment by RobertPaasche** [comment]
Hi i can confirm the first post, in editor is everything fine but not in the ui.

**Comment by robconrad** [comment]
+1

**Comment by webron** [comment]
This should be resolved in 3.0. Please reopen otherwise.

**Comment by rlogiacco** [comment]
@webron do you mean swagger-ui version 3.0? Is this the upcoming release? The latest downloadable version is still in the 2.x range....

**Comment by rlogiacco** [comment]
Problem is still there, using latest dist `3.0.7`: if that was previously gone it might be a regression...

I can get around this issue by removing a direct circular dependency with ClassA containing a list of ClassA, but that destroys my API

```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at swagger-ui-bundle.js:9717
    at j.__iterate (swagger-ui-bundle.js:9717)
    at n.r.__iterateUncached (swagger-ui-bundle.js:9717)
    at W (swagger-ui-bundle.js:9717)
    at n.T.__iterate (swagger-ui-bundle.js:9717)
    at n.forEach (swagger-ui-bundle.js:10952)
    at swagger-ui-bundle.js:9717
    at Ze.pe.withMutations (swagger-ui-bundle.js:10952)
    at Ze (swagger-ui-bundle.js:9717)
    at n.toOrderedMap (swagger-ui-bundle.js:10952)
```

**Comment by rlogiacco** [comment]
I confirm it was some sort of regression: latest working version is `3.0.4`, starting with `3.0.5` the `Resolver errorMaximum call stack size exceeded` is back.

Please re-open

**Comment by webron** [comment]
There's a separate ticket for that, no need to reopen.
