### ISSUE TITLE
Very slow loading times

### ISSUE THREAD

**Issue by replaysMike** [swagger-api/swagger-ui#1919]
I commented on this in an older issue, but I'm going to open a new one for performance issues.

I've got 45 api endpoints and am running swagger-ui under Swashbuckle (.Net) latest version. It currently uses swagger 2.1.3.

Before I started messing around it was taking over 4 minutes to display the endpoints UI. I went in and set the highlightSizeThreshold to 1, and finally just commended out the highlight-7-3 lib altogether. I did get a speed increase of about 50%, but a 2 minute load time is still very unacceptable.

Are you aware of what is causing the severe performance problems, and have an ideas to solve it? This isn't a huge API yet, but it will become one and I'm concerned about any attempt to support swagger at this rate.

I confirmed the backend is serving the requests in under a second, and the schema is around 1MB.

**Comment by fehguy** [comment]
Hi, the best way to help with this is to share the spec so we can profile it.

**Comment by replaysMike** [comment]
sure thing... here it is. I prettyfied it just for readability, but it's minified in the response.


[apischema.txt](https://github.com/swagger-api/swagger-ui/files/107271/apischema.txt)

**Comment by replaysMike** [comment]
I tried myself to profile it, but it just locks up the chrome tab.

**Comment by fehguy** [comment]
Thanks.  we're looking into this now, it may take a bit to sort out the root cause (and yes, I can reproduce it).

**Comment by collaborator99** [comment]
There seems to be a huge slowdown from rendering in version 2.1.0 to 2.1.1.  

With a Swagger "spec" with 19 operations, from the moment  "fetching resource list" message  appears to the operations list appearing, it went from almost instant (1 second) in version 2.1.0  to about 23 seconds! in 2.1.1.

**Comment by fehguy** [comment]
As the support for remote references has been added, the slow down _usually_ occurs when something goes wrong in fetching them (i.e. a 404 or inability to resolve a remote reference).  The _code_ for rendering a spec has not changed enough to cause what you're seeing.

@collaborator99 do you use remote references?  If you have a spec to share, it will help.

**Comment by replaysMike** [comment]
It's probably something small as it usually is, if I was familiar with the code base I'd be more help. I'll try to dig in myself this week.

**Comment by simonmurdock** [comment]
Also suffering from very slow performance on a very fast machine. For now I have attached my chrome timeline which you should be able to load into your timeline to get a full breakdown of what's going on. About 60% of my API is actually added right now and taking 15 seconds or thereabouts.

![1](https://cloud.githubusercontent.com/assets/5403478/12911617/ac96abae-cf0b-11e5-8a74-7aa80d6aa123.PNG)

[swaggerTimelineRawData-20160209T085821.zip](https://github.com/swagger-api/swagger-ui/files/122769/swaggerTimelineRawData-20160209T085821.zip)

I can also provide my swagger json privately if needed.

**Comment by fehguy** [comment]
Try setting the highlight threshold lower when initializing swagger-ui:

```
highlightSizeThreshold: 100
```

We're currently working on some performance issues around this right now.

**Comment by simonmurdock** [comment]
@fehguy ran latest version again with `highlightSizeThreshold: 1` and still the same issue, call stack exceeded after around three items are shown on the main screen:

![capture](https://cloud.githubusercontent.com/assets/5403478/12973967/569e0a14-d0a8-11e5-9432-a4f631eac1c9.PNG)

Pattern does look a little different though. Unfortunately I don't know a whole lot about backbone views or I'd be of more use.

**Comment by webron** [comment]
@simonmurdock - if you can share your swagger.json with us it would be a huge help for investigating it further.

**Comment by simonmurdock** [comment]
Hi @webron I've emailed it

**Comment by simonmurdock** [comment]
Any updates? @webron

**Comment by webron** [comment]
@bodnia? :)

**Comment by bodnia** [comment]
@webron it wasn't merged into master yet.

**Comment by bodnia** [comment]
PR for this issue is https://github.com/swagger-api/swagger-ui/pull/1956

**Comment by replaysMike** [comment]
I'll check out this PR however if you note my initial post, I had disabled highlight completely for my tests. It does indeed slow down the load time by a lot, however it is still painfully slow even without highlight.

**Comment by fehguy** [comment]
Sure thing @replaysMike.  There are multiple fixes going on, one was highlight which can now be configured away to be disabled completely.  Another with references (https://github.com/swagger-api/swagger-js/pull/710, not yet merged into the UI).  I'm hoping those two make a big difference, they will  at the very least help us isolate things.

**Comment by simonmurdock** [comment]
The issue is that everything in signature.js is incredibly slow and is all being processed up-front. It should be deferred until you click that particular path/route. I think these accounted for 50% of the issue.

Those calls being:
`getModelSignature`
`createJSONSample`
`getParameterModelSignature`
`createParameterJSONSample`
`createSchemaXML`
`createXMLSample`
`getPrimitiveSignature`

**Comment by simonmurdock** [comment]
The issue is that everything in signature.js is incredibly slow and is all being processed up-front. It should be deferred until you click that particular path/route. I think these accounted for 50% of the issue.

Those calls being:
`getModelSignature`
`createJSONSample`
`getParameterModelSignature`
`createParameterJSONSample`
`createSchemaXML`
`createXMLSample`
`getPrimitiveSignature`

I've since started developing my own UI to parse swagger API json files, and do roughly what Swagger-UI does. Admittedly it's not doing any of the model stuff yours is, but it's deferring everything and loading a UI in < 600ms. Should be possible to get swagger-UI that fast.

**Comment by MisterWil** [comment]
Are there any updates on this? Seems that this as well as #1804 are related. Like @simonmurdock above, I was also having extremely slow performance on a much smaller API and the master got stuck in a createSchemaXML loop.

**Comment by simonmurdock** [comment]
I've just abandoned swagger completely.

**Comment by ponelat** [comment]
That's very sad

**Comment by Helmsdown** [comment]
Just ran into this. I can provide my swagger spec privately.

I was running the dist of swagger-ui:2.1.4. I pulled the dist from master and its much better!

+1 releasing a new version of swagger-ui

**Comment by webron** [comment]
@Helmsdown - we're close to releasing a new version. If the performance of master is not enough, please share the spec. You know how to reach us ;)

**Comment by nikhilgk** [comment]
Here is publicly available spec that is unusable with v2.10.3. The spec file is 4MB in size.
https://docs.oracle.com/cloud/latest/salescs_gs/FAAPS/swagger.json

**Comment by fehguy** [comment]
Swagger-ui just received an update which dramatically speeds up loading times.  Please try master, which uses swagger-js 2.1.17.

**Comment by replaysMike** [comment]
Will be reviewing this today. Would love to be able to go back to using Swagger-UI.

**Comment by fehguy** [comment]
Please do share your findings

**Comment by michaelrepucci** [comment]
I just pulled the latest swagger-ui from dist on master, and while it's better, I still have painfully slow performance on a REST API with 50 read-only (GET) endpoints. The minimized [swagger.json](https://github.com/swagger-api/swagger-ui/files/404083/NeuroReadback.swagger.json.txt) is 94.4 KB and, itself, loads very quickly. But both Firefox and Chrome complain of unresponsive scripts when loading it through the swagger ui. I'm completely new to swagger so mostly wondering if this is a limitation of swagger itself, or related to my REST API.

**Comment by webron** [comment]
@michaelrepucci - thanks, that's great. Not great that it gets stuck, but it's it's rather that you provided the spec - that helps us a lot analyzing what's causing these issues and tackling them one by one. I can confirm that this is indeed painfully slow with the current master.

**Comment by fehguy** [comment]
Looks like an issue with XML rendering, I'm getting a max call stack exceeded.

**Comment by gwynjudd** [comment]
I'm seeing very slow page loading times - we are using swagger-ui 2.1.4 from swashbuckle. Out swagger definition is around 6Mb in size so it's pretty big? It took around 90 seconds to render in the client

**Comment by gwynjudd** [comment]
I tried master branch - I found that rendering time seemed to be much improved in that I can see the UI will all of the controller names fill in somewhat faster. However, the page is completely unresponsive for some time after (a few minutes) and I see the chrome "this page is unresponsive" message appear several times before I can interact with it.

**Comment by gwynjudd** [comment]
Please let me know if you would like to get a swagger spec file from me

**Comment by webron** [comment]
@gwynjudd - yeah, that's the best way to help us solve performance issues, much appreciated.

**Comment by simonmurdock** [comment]
I also emailed my json 5 months ago.

**Comment by webron** [comment]
@simonmurdock - I'm afraid I can't find your spec. 

We're working on a major update to swagger-ui and collecting specs that raise issues in the current version, so we can make sure to address those before pushing it out.

**Comment by simonmurdock** [comment]
sent again

**Comment by webron** [comment]
Got it, thanks. We'll add to our use cases.

**Comment by webron** [comment]
@simonmurdock from quickly looking at it (with the current version of swagger-ui), it looks like the issue is similar to @michaelrepucci's. The XML rendering takes too long. Removing the `application/xml` from the spec makes the rendering significantly faster. Obviously, this is not a solution, just helping us isolate the issue.

**Comment by icaro56** [comment]
I use the last swagger ui version. After I click on Explore, the ui stay loading and crash on Chrome.
![slow_loading](https://cloud.githubusercontent.com/assets/7433049/17789643/82237a56-6569-11e6-8071-b84e5aa4c706.png)

**Comment by webron** [comment]
@icaro56 - just like with everyone else, we can't do much without a spec to reproduce the issue.

**Comment by icaro56** [comment]
What is a spec? I sent to you the swagger.json. I think swagger ui is slow because the swagger.json is big, 100KB. 

    Em Quinta-feira, 18 de Agosto de 2016 17:55, Ron <notifications@github.com> escreveu:
 

 @icaro56 - just like with everyone else, we can't do much without a spec to reproduce the issue.—

**Comment by icaro56** [comment]
Is Spec that?
My pom.xml
<groupId>io.swagger</groupId><artifactId>swagger-jaxrs</artifactId><version>1.5.9</version>

    Em Quinta-feira, 18 de Agosto de 2016 17:59, Ícaro Goulart Faria Motta França <icarogoulart@yahoo.com.br> escreveu:
 

 What is a spec? I sent to you the swagger.json. I think swagger ui is slow because the swagger.json is big, 100KB. 

    Em Quinta-feira, 18 de Agosto de 2016 17:55, Ron <notifications@github.com> escreveu:
 

 @icaro56 - just like with everyone else, we can't do much without a spec to reproduce the issue.—

**Comment by webron** [comment]
Did you put it in a different ticket? It's not here...

**Comment by icaro56** [comment]
Hi, 
I attach now. I read many topic on many forums and I did not find nothing.
Thanks    Em Quinta-feira, 18 de Agosto de 2016 18:10, Ron <notifications@github.com> escreveu:
 

 Did you put it in a different ticket? It's not here...—

**Comment by webron** [comment]
You can't attach files with email, you have to do it through github's interface.

**Comment by icaro56** [comment]
[swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/427012/swagger.json.txt)

**Comment by simonmurdock** [comment]
yes see https://github.com/swagger-api/swagger-ui/issues/1919#issuecomment-187456236

**Comment by icaro56** [comment]
@simonmurdock I like very much swagger documentation. I was using Enunciate doc. Are there another lib doc similar to swagger?

**Comment by webron** [comment]
@icaro56 just tried loading your spec in the latest version in both Firefox and Chrome - loads quickly and doesn't crash. Are you sure you're trying the current latest?

**Comment by icaro56** [comment]
Yes. In top from swagger-ui.js is 

/**
 * swagger-ui - Swagger UI is a dependency-free collection of HTML, JavaScript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API
 * @version v2.2.0
 * @link http://swagger.io
 * @license Apache-2.0
 */

If you do not pass the apikey is fast, but after you inform the api key all services will are available. I think send you only swagger.json with get services.

Sorry, now with all services
[swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/427610/swagger.json.txt)

**Comment by webron** [comment]
Thanks! Now I'm able to reproduce it. We'll use it in our testing as well.

**Comment by gwynjudd** [comment]
Hello,

I have pasted an anonymised version of my spec file here:

https://gist.github.com/gwynjudd/23c09d5a99463fddc0938f3ff8f3c64e

It is around 7Mb in size, and it takes several minutes when loading into chrome on my PC before the UI becomes responsive again.

**Comment by webron** [comment]
Thanks @gwynjudd. It's a huge spec, definitely takes a long time to load. Since it's hard to navigate through and check it manually - quick questions - do all tags have exactly the same set of operations with only one specific part of the path being different?

**Comment by cabbonizio** [comment]
There's a huge number of re-usability and condensation opportunities in that spec @webron.  That is kind of equivalent to me having a separate URI for each product in my corporations catalog which is nearly 100K products.  Apologies if I'm missing something here.

**Comment by webron** [comment]
@cabbonizio I'm not sure about the context of your message. If it's about @gwynjudd's spec, then there's potentially a way to minimize the spec making it smaller in general, regardless of the UI.

**Comment by gwynjudd** [comment]
@webron yes that is true at the moment, but that may change as we develop our API further and expose more functionality to the entities. @cabbonizio it is more like having a separate URI for each table in a database - we wouldn't have a separate URI for each product, but we would have a separate URI for (say) the products table. We can potentially filter some of them out, but there are likely to be hundreds that would need to be exposed for some use or other

**Comment by webron** [comment]
@gwynjudd Putting the current performance issue aside, you can really speed things up by making a few simple changes to your spec (I don't know if it's generated or handwritten). You can condense the operations that only have the different entity by making the entity name a path parameter, with an enum providing the options for the different entity names (again, all that assumes they are indeed identical). You can apply multiple tags per each entity if needed. It will render the same way in the UI, but the file itself will be *substantially* smaller, making network faster and parsing as well. The downside is that all operations under all the tags will still show all the options for the enum, not just the one applied to the tag - not sure if that's acceptable for you.

In the future, if you need to apply special operations for entities, you can do the same by applying only the relevant tags and the relevant enum values for those specific operations.

**Comment by gwynjudd** [comment]
@webron It's generated from metadata - I are using Web API and swashbuckle to do all of that hard work. Can you expand on how to make the entity name into an enum? I might have to do some research into seeing if swashbuckle is flexible enough to make that possible. What is a "tag" in this context?

**Comment by webron** [comment]
@gwynjudd - got it. Not sure how much control Swashbuckle provides you, but you can its author about it, he's a great guy. In any case, it's fairly simple, just like any other parameter type. So assuming you have the path`/v1/{entity}/ops` then you'd define the `entity` parameter as:
```yaml
        - in: path
          name: entity
          description: Entity type
          required: true
          type: string
          enum:
          	- Entity1
          	- Entity2
          	- Entity3
```
That effectively says that these are the only 3 values that will be accepted.

The tags are are organizational tool to group operations. A single operation can actually have multiple tags, putting a single operation in multiple groups. If you look in swagger-ui, it uses the tags to group the top-level operations - in your case it's the entity names.

**Comment by gwynjudd** [comment]
@webron thanks for that, after spending literally 2 minutes looking it looks like I might be able to implement an operation filter along with some kind of rework of how the controllers are generated. 

Instead of having one operation for each entity type (what I do now), I would have only 1 operation for the whole thing. Then in the path `/v1/folder/{controller}/`, the `controller` parameter would have to be an enumerated type as you defined above, instead of being the name of the controller definition in Web API.

Swashbuckle generates the first tag for each operation:

> Each operation can be assigned one or more tags which are then used by consumers for various reasons. For example, the swagger-ui groups operations according to the first tag of each operation. By default, this will be the controller name but you can use this method to override with any value.

By the looks of that, I would then have to add one tag for each entity name to the operation? Then get swagger-ui to group by those tags?

**Comment by webron** [comment]
@gwynjudd that is correct. Technically you don't *have* to use multiple tags, it depends on what you'd want to achieve (and only you can decide that). In swagger-ui, tags will affect the grouping - so the same operation will appear for each tag (entity) that you define. This is not strictly needed as it's indeed the same operation, but it's more of a documentation choice.

For code-generation, tags can be used to organize operations into classes. Again, strictly speaking, if the entities have *the same* operations and do not use input/output that's specific to those entities, you don't necessarily need that.

**Comment by Zapnologica** [comment]
Any update to this? I am experiencing a similar issue with reasonably small api. However mine takes more than 15-20 minutes to show up. I have asked a SO question about it.   [http://stackoverflow.com/questions/39220272/swagger-ui-hangs-on-fetching-resource-list-please-wait](url)

**Comment by PeterBrende** [comment]
I am having severe performance issues when adding relationships between objects. We use Nhibernate, and have many parent-child relationships between the entities used in our Web API OData services. I tried removing all relationships (Swagger UI is very quick). One by one, I started adding back relationships. The performance degraded very quickly until it got to the point where it just processes for several minutes before dying (I believe because of memory). I have attached the spec.
[SwaggerSpec.txt](https://github.com/swagger-api/swagger-ui/files/457017/SwaggerSpec.txt)

**Comment by gwynjudd** [comment]
@webron after more investigation, I found that this approach wasn't going to work. If you recall, we initially thought that my schema consisted of a great many tags with all of the same operations. It turns out that after further development, the operations for each entity type either return or take parameters of different types. This meant that the idea of factoring out the operations and associating them with tags wasn't going to work. Do you have any further ideas for improving performance? For now, I am filtering the operations and entity types so that the API document size doesn't become too massive.

**Comment by webron** [comment]
@gwynjudd - would be hard to say without seeing a (current) example of the spec. Are you able to share that?

**Comment by gwynjudd** [comment]
@webron I'll see if it becomes high priority for me or not. Currently I am jumping around between a number of projects.

**Comment by webron** [comment]
@gwynjudd no worries, ping me when you can.

**Comment by wauk** [comment]
domaindrivendev/Swashbuckle#891
I think this is the issue and everyone is logging the issue in the wrong place

**Comment by michaelrepucci** [comment]
@wauk I don't fully understand the difference between Swashbuckle and Swagger-UI, but unless Swashbuckle is a dependency of Swagger-UI that is completely transparent to the use of Swagger-UI, I don't think domaindrivendev/Swashbuckle#891 is my problem.

**Comment by webron** [comment]
@wauk not all the issues raised here are related to Swashbuckle.

@michaelrepucci - Swashbuckle is responsible for generated the Swagger/OpenAPI spec documenting the API. swagger-ui (this project) is the visual renderer of a spec in a human-friendly format. Swashbuckle embeds swagger-ui in it to help its users get a nice UI, but they projects are not directly related.

**Comment by wauk** [comment]
They are related in the aspect that Swashbuckle serves the resources for the swagger-ui interface if you integrated using Swashbuckle  and I agree that its not responsible for all the issues here but most of the people using Swashbuckle should experience some sort of slowness especially when some latency is added to a request to fetch a resource for the swagger-ui

**Comment by michaelrepucci** [comment]
I'm still confused whether I'm using Swashbuckle. What @webron said makes me think I am, because something Swagger related is generating the swagger.json for me. Here's what I do.

I put a copy of the swagger-ui code that I pulled from this repo directly into my Java EE web resources, then annotated my REST facades with Swagger annotations. It almost seems like magic that the swagger.json is created from those annotations - I provided this previously - and the UI displays this swagger.json correctly when I open the swagger-ui index.html, just very slowly.

Was Swashbuckle involved in this process at any point? If so, where?

**Comment by webron** [comment]
@michaelrepucci Swashbuckle is a .NET integration that exposes the swagger.json from the code - so... unlikely that you use it. For Java, it depends on which REST framework you use as there are different libraries for different frameworks.

**Comment by michaelrepucci** [comment]
@webron We're using JAX-RS as implemented by RESTEasy on Wildfly 10.

**Comment by webron** [comment]
@michaelrepucci then you're probably using swagger-core

**Comment by andrenpt** [comment]
If the API has more than a certain amount of methods swagger-ui just times-out.
If required I can provide in private the json file.

Thanks

**Comment by webron** [comment]
@andrenpt please do, email is in my profile.

**Comment by ongobongo** [comment]
It was fixed in [this commit](https://github.com/domaindrivendev/Swashbuckle/pull/910/commits/31db90977fc6598c8dbe27c05b13bb7d705ac695) which is included in 5.5.1 (5.5.2 is latest public nuget version)

**Comment by replaysMike** [comment]
Confirmed this is still an issue. UI times out and crashes the tab with out of memory issue. Schema is only 30kb in size and the majority of the size is with model definitions.

**Comment by webron** [comment]
@replaysMike - please do, it'd be helpful.

**Comment by replaysMike** [comment]
Attached is the swagger schema that causes the UI to barf.

[api_v1.zip](https://github.com/swagger-api/swagger-ui/files/725326/api_v1.zip)

**Comment by webron** [comment]
Great, thanks! I'll test it shortly.

**Comment by replaysMike** [comment]
any luck with the testing? I'm getting close to switching to a custom implementation, we're pretty much out of luck with this library unless there is a fixable issue with the schema.

**Comment by webron** [comment]
@replaysMike we're actually in the process of a major update to the tool, which will include a lot of performance improvements as well. Testing your spec, it _loads_ okay, but we can still improve the performance in some aspects to it.

**Comment by robertcsakany** [comment]
I have same problem with the attached swagger spec - impossible to get response from UI. Its a simple example application. It is generated from CXF. I know this is relatively large, but as a matter of fact I dont think a REST api endpoin't operation counts have to be less then ten. The microservice world only just a part of a real world, our application have several endpint operations. Maybe my spec is not optimal, maybe I have to forget tags - If you say so I can optimize. I've tried some of them, but none of them helped.

If there is no chance that the Swagger UI frontend will be performant I thin about to make some static HTML generation.

Is ther eany chance this type of specs will be supported?

[swagger_car.zip](https://github.com/swagger-api/swagger-ui/files/742567/swagger_car.zip)

**Comment by replaysMike** [comment]
@webron I think we can close this thread. I was able to resolve all the issues purely at the schema generation side with Swashbuckle. There were multiple issues, which I suspect other users are also encountering (though I think it would be good to detect and prevent these conditions in the UI, as it seems to be related to following circular $ref's).

To summarize, this is how I fixed my issue:

- Our API was referencing/returning Entity Framework models in the API, and this causes Swashbuckle to include them (and follow all references) which bloats the size and introduces all sorts of cross-model references. Fixing this issue solved a majority of the problems encountered with swagger validation and swagger ui.

- Turning off fully namespaced definitions in Swashbuckle reduced the overall size of the output. Had to resolve some conflicting model names to fix the need for this.

- Removing models that had parent/child relationships. It seemed in some cases this was not as much of a problem.

After resolving this, swagger UI loads in under a second and it's a fairly large API.

**Comment by webron** [comment]
@replaysMike wow, thanks for the update. It's amazing how tuning can make such huge impacts at times. Hopefully, others will find this useful as well.

If you don't mind, I'll keep this issue open because other hitched a ride on it and brought up similar yet different issues all related to performance. We're getting close to releasing a major update that will address a lot of issues, including performance, and I'd like to use the tickets to manage what we're trying to solve.

If you feel strongly about it, we can still close the issue and open a new one instead.

**Comment by replaysMike** [comment]
absolutely, no this is an epic thread with a lot going on. I'll look forward to the upcoming updates and will test what I can with the new releases.

**Comment by dimitertodorov** [comment]
Running into a similar issue. In my case I am using grape-swagger to generate my swagger automatically.


[todorovdi_nmdb_swagger.zip](https://github.com/swagger-api/swagger-ui/files/755745/todorovdi_nmdb_swagger.zip)

**Comment by yyy717yyy** [comment]
Just run into the similar issue. It seems that the problem is due to the definition array type. I defined input field as an array. But did not specify the actual item. There is no error in swagger editor. But it caused the hang problem in swagger UI.
definitions:
  Logger:
    type: object
    required:
    - loggerBasicInfo
    - input
    - output
    properties:
      loggerBasicInfo:
        $ref: '#/definitions/LoggerBasicInfo'
      **input:
        type: array
      output:
        type: array**

**Comment by webron** [comment]
@yyy717yyy you can't have type array with no `items`.

**Comment by webron** [comment]
Everyone, we have released 3.X Please give it a try and let us know of any performance issues.

**Comment by michaelrepucci** [comment]
Thanks for the update. But forgive me for being incompetent. I can't get this to work. With 2.X I simply included the contents of /dist in my Java EE WAR, and the annotation-generated swagger.json loaded (albeit slowly). With 3.X including the contents of /dist displays an empty page.

If, instead, I open /public/index.html on my desktop (outside of the deployed application), and point it to my swagger.json, I get the following "Failed to load spec" error: {"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://127.0.0.1:8080/NeuroReadback/rest/swagger.json"}]}

My swagger.json is the same as I posted here before, as our API is unchanged. Is there something I'm missing? I did speed read the documentation.

**Comment by webron** [comment]
@michaelrepucci - can you check your browser's console logs for additional errors?

**Comment by michaelrepucci** [comment]
See screenshots below of contents deployed in app and Firefox console error.

![image](https://cloud.githubusercontent.com/assets/6200989/24303517/b81c7512-108c-11e7-905e-6340cca7bd2a.png)

![image](https://cloud.githubusercontent.com/assets/6200989/24303416/4e24765a-108c-11e7-9c68-f7381c508889.png)

**Comment by webron** [comment]
Is that with the index.html from public? you shouldn't use the one in dist.

**Comment by michaelrepucci** [comment]
Maybe you could explain to me how I'm supposed to use swagger-ui 3.X. It's not clear to me from the documentation. I have a Java EE project that is packaged into a WAR. With swagger-ui 2.X, I simply copied the contents of the swagger-ui /dist folder into the web root of my WAR, and it worked (albeit slowly). With swagger-ui 3.X, I did the same thing and got what you see above. What should I do instead?

**Comment by webron** [comment]
It's slightly more complicated - we'd need to write documentation for that (though I'm hoping for a simpler change). In the meantime, would suggest running it locally and just point it to your spec instead.

**Comment by michaelrepucci** [comment]
Oh, that's unfortunate, as we prefer to serve the docs with the application. But I now see why I got the "Failed to load spec" error that I mentioned above when I ran it locally: the console indicates that it was a CORS restriction, which is of course described thoroughly in the documentation. Would have been nice to see that reason in the "Failed to load spec" error message.

**Comment by michaelrepucci** [comment]
After enabling CORS, I did test the locally run swagger-ui, and it is perfect in terms of responsiveness, no lag. Is there an approach I can use to try to deploy this in my Java EE application?

**Comment by michaelrepucci** [comment]
Just noticed that, oddly, even with CORS enabled, the swagger-ui still shows me that same error ({"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://127.0.0.1:8080/NeuroReadback/rest/swagger.json"}]}) at the bottom-right of the page. The swagger docs look correct though, except that on my dev environment the app is on port 8080 while the "Try it out" button seems to expect port 80.

**Comment by webjoel** [comment]
I have an API that contains more than 100 paths, after loading in swagger ui and clicking on the endpoint takes a lot time to open, without even showing a "loading", this I have not yet mapped the responses of the path.

Is there any way to improve performance? Lazy loading / rendering? My swagger.json has 128 KB.

Version of Swagger UI: 3.1.4.

Until this is resolved I'm using ReDoc.

**Comment by ponelat** [comment]
We need to optimize the amount of re-renders. This is definitely doable, its just work that needs to be done, such that after loading ( ie: after the resolver, yaml, etc has run ) - then the UI should be reasonably fast on opening and collapsing an endpoint. 

A possible reason it isn't, is likely due to the number of containers ( components tied to global state ) that are re-rendered as a result of toggling the `layout.shown` state.

**Comment by wahyufrombandung** [comment]
My solved solutions (Using C# .Net in visual studio 2015):
on your code, check the upper part of every controller that needs to be accessed from swagger, please add comments below:
`/// <summary>
        /// 
        /// </summary>
        /// <param name="fromDate"></param>
        /// <param name="toDate"></param>
        /// <param name="transactionType"></param>
        /// <param name="options"></param>
        /// <param name="mini"></param>
        /// <returns></returns>`

then between the controller and the comments, put the swagger access as follows:
`[VersionedRoute("your-versioned-route")]
        [Authorize(Roles = "your roles")]
        [ResponseType(typeof(return type ))]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(return type))]
        [HttpPost] //access method
        [ActionName("yourControllerActionName")]`


NB: don't forget to make sure the return type provided by the controller is the same as the return type you provide to swagger.

hope it can helps

**Comment by gsviteri** [comment]
Hi, I am still having performance issue in a relatively small spec file (16 tags + 107kb).
Running an swagger old version the API loading + rendering time was nice and fast. 
Due to new specification combined with the redesign of our website, we decided to update SwaggerUI and after updating to tag:v2.2.10 the loading time goes up to 38seconds. 
3 days ago a new version has been released but sadly for me it is even worse in the sense that it freezes Chrome and I can't get any result, after a minute or so, it renders the page but still very clanky.
I have no problem sharing my spec with the developers, but I can't share it here. How do I sent it to you ?

This is how I am creating, all with default values. ValidatorURL does not really make any difference.
```
const ui = SwaggerUIBundle({
            url: window.location.origin + deployPath + "/v2/api-docs",
            dom_id: '#swagger-ui',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout",
            validatorUrl: null,
            tagsSorter: "alpha",
            docExpansion: "none"
        });

        window.ui = ui;
```

Thanks for you help
Br

**Comment by webron** [comment]
Thanks everyone for the feedback. Each API document that we get helps us with evaluating the different issues. As you can imagine, performance tuning is an ongoing process and we slowly make improvements for it. There's are a few major changes in the works that would benefit performance and other parts of the app - but those take time.

For those of you who can't share the definitions publicly, you can send them to @shockey or myself - our emails are found in the profiles.

**Comment by iplayfast** [comment]
https://github.com/swagger-api/swagger-editor/issues/1541 has example json file that crashes it. Used this code for 2 days, and it appears to be useless.

**Comment by nijinillath** [comment]
Hi @webron , same issue with the page unresponsive while loading swagger UI due to json size (750 KB), the swagger json is code generated using swagger-jersey2-jaxrs. I have send you the Json in email. Thanks in advance.

**Comment by Freemahn** [comment]
@nijinillath try to collapse 'models' section. After this swagger UI will become responsible and fast again.

**Comment by nijinillath** [comment]
Thanks @Freemahn for the response, but using docExpansion: "none" also the UI page unresponsive.

**Comment by nijinillath** [comment]
Hi Team, did you get a chance to re-check on the UI page unresponsive issue due to the size of json ?

**Comment by webron** [comment]
We regularly investigate and provide small performance improvements over time. This ticket encompasses a range of such improvement. We can't say which improvement will fix whose issue, so it's best to keep checking with newer releases.

**Comment by shockey** [comment]
FYI: if the Models section is your performance bottleneck, the most recent release (3.4.4) contains improvements that are likely to improve your experience.

**Comment by nijinillath** [comment]
Thanks Team, appreciate the response.. Will check on the newer releases. As of now "SwaggerUI-Angular" worked for my load.

**Comment by heldersepu** [comment]
Adding comment from #3911 
http://nhc-noaa.azurewebsites.net/swagger/ui/index?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=Api

On that case the json is relatively small ~40K but the UI takes very long to show

**Comment by heldersepu** [comment]
@webron try that last link I posted, the key is the `defaultModelsExpandDepth=5` with 0 it shows right away. I had some debate with @shockey about that on #4248

**Comment by msankhala** [comment]
I am using the swagger hub and my API spec contains 1000 lines and it has become extremely slow. Even though I have collapsed all of my schema and a few paths but It is still slow.

**Comment by heldersepu** [comment]
@msankhala Can you share your spec?
Have you tried reducing the spec (maybe try with less paths) see if something stands out as the main issue?

**Comment by zekeriyakoca** [comment]
I faced the same issue after adding [ResponseType] attribute to my endpoints. Some of the endpoints was returning complex model class and this was causing the problem in my case. I removed this attribute for these endpoints and it's solved. ResponseType was not mandatory for my project and I skipped this feature, but if you need it, you can try to find a solution to restrict model serializing dept.

**Comment by heldersepu** [comment]
@zekeriyakoca what you mentioned `[ResponseType] attribute` is not a swagger-ui feature, a quick search on the code returns nothing:  
https://github.com/swagger-api/swagger-ui/search?q=ResponseType&type=Code

best you can do is attach your spec here so the team can look into it

**Comment by zekeriyakoca** [comment]
> @zekeriyakoca what you mentioned `[ResponseType] attribute` is not a swagger-ui feature, a quick search on the code returns nothing:
> https://github.com/swagger-api/swagger-ui/search?q=ResponseType&type=Code
> 
> best you can do is attach your spec here so the team can look into it
[ResponseType] asp.net attribute used by ApiExplorer to know what type a method returns. Swagger should be using this attribute to documenting the return type. 
![ResponseType Attribute](https://user-images.githubusercontent.com/35925772/77562332-ee63eb00-6ed0-11ea-884f-1b8ceea17cdd.JPG)

DbsDocument cannot be serializable because of circular dependency. This code cause the swagger index page to be loaded in 20-30 secs and when I try to expand the request in swager ui panel, it's frozen.

**Comment by heldersepu** [comment]
@zekeriyakoca  that screenshot looks like C# maybe you are using swashbuckle, but that is not directly related to this project...
and no, at the moment, there is nothing to restrict the serialization depth, once someone clicks on the model it will expand all the way

**Comment by spaasis** [comment]
Just noting that this issue is making it rather difficult to use OData (https://docs.microsoft.com/en-us/odata/webapi/first-odata-api) since it "relies" on accessing the ORM model via the API. This in turn might turn people away from OpenAPI towards e.g. GraphQL

**Comment by heldersepu** [comment]
> Just noting that this issue is making it rather difficult to use OData (https://docs.microsoft.com/en-us/odata/webapi/first-odata-api) since it "relies" on accessing the ORM model via the API. This in turn might turn people away from OpenAPI towards e.g. GraphQL

I don't think this is a problem with all OData projects and swagger-ui, quite the opposite only those most project should be just fine, only those with complex models with a lot of nesting might have issues and those should be a minority.

**Comment by spaasis** [comment]
@heldersepu Sure, might be that most projects don't actually get hit by this. I'm working on environmental data, which by it's nature is very much linked together, so I've been bit by this in practically every OData API we're supplying via OpenApi. 

The workaround thus far has been to exclude some navigation properties from the swagger.json to stop some of the cycles, but this will cripple the API usage somewhat..

I think some of this could be better handled if the renderer would skip some of the redundant loops.
e.g. If I have a relation A-B-A (quite standard in OData to provide navigation properties both ways), the UI will render
- A fully
  - B fully
    - A fully
      - B fully
        - A as empty

When it could be
- A fully
  - B fully
    - A as empty

The generated example value gets really bloated when some classes example data is printed many times over

**Comment by heldersepu** [comment]
@spaasis just to clarify ... let's not mix `OpenApi` and `swagger-ui` ...

This is not a problem on the OpenApi Specification, you can provide the full swagger.json to any one and they can generate a client just fine, then make calls to the endpoints without any problem.
Here is an example:
https://swagger-net-test.azurewebsites.net/api/NestedSwag/9

The problem is expanding some of those models in the swagger-ui, see here: 
https://petstore.swagger.io/?url=https://swagger-net-test.azurewebsites.net/api/NestedSwag/9
That is the same spec but if you try to expand `Test0` model very likely browser will crash

**Comment by spaasis** [comment]
@heldersepu Certainly! I was a bit unclear. What I meant by "..turn people away from OpenAPI" was that if their model cannot be utilized via the de-facto default UI of OpenAPI, then that might push them to alternative solutions such as GraphQL (or just a different UI such as ReDoc). Our models that struggle with the swagger-ui work beautifully in the client generation.

**Comment by heldersepu** [comment]
@spaasis have you tried a complex model on ReDoc?
http://redocly.github.io/redoc/?url=https://swagger-net-test.azurewebsites.net/api/NestedSwag/9
It crashes in a worst way than swagger-ui

**Comment by spaasis** [comment]
@heldersepu In the two cases I tried ReDoc, the initial load takes way longer than swagger-ui, but after that it worked fine. Contrast that to swagger-ui where the initial load is fast, but opening an endpoint takes ages and makes the entire ui unresponsive for rest of the session. So yeah, neither are perfect

**Comment by oscarguinane** [comment]
Ok, so to fix this, can we just replace the default selected response example to **schema** instead of **value**? The schema loads just fine but the value crashes the page for me.

<img width="608" alt="Screen Shot 2023-01-20 at 17 29 EST" src="https://user-images.githubusercontent.com/4477702/213816789-2189b596-7841-4ea6-b3ed-e53039de9828.png">

**Comment by oneVcard** [comment]
> To fix this, can we just replace the default selected response example to **schema** instead of **value**? The schema loads just fine but the value crashes the page
> 
> <img alt="Screen Shot 2023-01-20 at 17 29 EST" width="608" src="https://user-images.githubusercontent.com/4477702/213816789-2189b596-7841-4ea6-b3ed-e53039de9828.png">

Is it possible to set the default to schema with some configuration? We use `@nestjs/swagger`

**Comment by appleseedexm** [comment]
Is there an update on this, is this on some kind of roadmap? The latest responses seem only partially related and its a very long standing issue. 
For our project this has lead to calling the FE endpoint on server startup to trigger the initial load which makes following requests faster, but looking at this issue I do wonder if it makes sense to look around for alternatives.

**Comment by yuryturing** [comment]
> Is it possible to set the default to schema with some configuration? We use `@nestjs/swagger`

Setting `swaggerOptions,defaultModelRendering` worked for  me.

```
SwaggerModule.setup('docs', app, document, {
    swaggerOptions: {
      docExpansion: 'none',
      // @see https://github.com/swagger-api/swagger-ui/issues/6787
      syntaxHighlight: false,
      defaultModelRendering: 'model',
    },
  });
```

**Comment by Mathias02** [comment]
This kind of problem sometimes has to do with the app optimization. I have tested the loading speed and didn't experience this issue on my machine. My Swagger UI version is -v5.20.1,I am using hp PROBOOK with Linux Mint and my browser is Firefox 137.0.1 and I am at 60% of my internet speed so I don't see this issue. Some other reasons can be the machine, the internet speed or the browser that one uses

![Image](https://github.com/user-attachments/assets/8ab3f89e-711f-4e5a-985f-b54ba50abc42)

![Image](https://github.com/user-attachments/assets/262e63d1-6603-41ad-af31-f79a9d9bb11b)

.

**Comment by ponelat** [comment]
Closing this out, as the issue is too old to capture the latest concerns with performance (I'm sure there still are performance improvements that can be made!). Since the start of this issue, SwaggerUI has been completely rewritten. And perhaps the notable perf increase is lazily loading operations (which get loaded as you expand an operation). 

If folks have particular issues, or issues with API documents, please open a new ticket.
