### ISSUE TITLE
Posting array in formData (multipart/form-data)

### ISSUE THREAD

**Issue by salva5234** [swagger-api/swagger-ui#2240]
Hello,

first of all, I want to thank you for your greate product.

I´am using swagger-ui version 2.1.4

I want to post an array with following configuration:

"name":"disease_ids",
"in":"formData",
"description":"disease_ids to add",
"type":"array",
"items":{
     "type":"integer"
},
"collectionFormat":"multi"

Because I also want to post a file in this request I use "multipart/form-data":

The posted Data looks like the following (as you see the ids are concatenated):

-----------------------------29903252427366
Content-Disposition: form-data; name="allergy_ids"

allergy_ids=576720da3252bacc1c8f388f&allergy_ids=576721063252bacc1c8f3891
-----------------------------29903252427366
Content-Disposition: form-data; name="disease_ids"

disease_ids=5767958dce7fd3b428b8fac2&disease_ids=576795aace7fd3b428b8fac4

But I need the following format (produced with postman, with id´s as separeted values):

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="allergy_ids"

576720da3252bacc1c8f388f
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="allergy_ids"

576721063252bacc1c8f3891
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="disease_ids"

5767958dce7fd3b428b8fac2
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="disease_ids"

576795aace7fd3b428b8fac4

I would be appreciated if you could help me.

Thank you a lot !!!

Salvador

**Comment by fehguy** [comment]
Please try master, this should be fixed now.

**Comment by yuxiaomin** [comment]
@fehguy In the latest 2.2.2 version I still see this issue. the Array parameter is not correct in request. Can you please take a look at it?

For example the string array parameter name is f_string_array the request payload looks like following

```
------WebKitFormBoundary7W2Kggzgqy43nh7W
Content-Disposition: form-data; name="f_string_array"

f_string_array=1&f_string_array=2&f_string_array=3
------WebKitFormBoundary7W2Kggzgqy43nh7W
```

The cURL is like this
`curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -F f_string_array=f_string_array=1&f_string_array=2&f_string_array=3 -F f_int=0  'endpoint_url'`

**Comment by fehguy** [comment]
OK well, two things.

First, with a collection type, you should specify the `collectionFormat`.  It may be a CSV, in which case what we are sending is correct.

However, I think what you're after is the `multi` collection format, which is not doing the right thing.  I'll open an issue in swagger-js to add this support.
