### ISSUE TITLE
Wrong CURL command for file upload params

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-ui#2259]
With a parameter in the swagger spec like

``` yaml
      parameters:
      - name: "file"
        in: "formData"
        description: "csv file"
        required: true
        type: "file"
```

Swagger-UI shows a curl command like

```
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: text/plain' -F @file.csv  ...
```

This is not correct curl syntax. It should be 

```
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: text/plain' -F file=@file.csv  ...

i.e. the key (param name) has to be in the form data part.
```

**Comment by webron** [comment]
@fehguy - I think you touched that part specifically a couple of weeks ago

**Comment by fehguy** [comment]
This is fixed in the master version of swagger-js, I'll try to get a release today so it can be updated here

**Comment by delenius** [comment]
FWIW, I am still seeing this issue in the current swagger-ui.

**Comment by rvpeters** [comment]
It appears this was fixed in 2.1.5 but it is broken in 2.2.10 (tried the same yaml file for both and the -F file=@/path/to/file appeared when using 2.1.5 but did not for 2.2.10). Is there a fix on the roadmap for this regression?

**Comment by webron** [comment]
This will be fixed in an upcoming major release.

**Comment by webron** [comment]
Should be fixed.
