### ISSUE TITLE
Path-level parameters are not displayed in the UI

### ISSUE THREAD

**Issue by xplicit** [swagger-api/swagger-ui#2791]
I have following definition of "Accept" parameter

```json
{
"name":"Accept",
"in":"header",
"description":"Accept Header",
"type":"string",
"required":true,
"enum":["application/json"]
}
```

If I put this declaration on `paths` level, then this parameter is not shown in UI and when I click "Execute" button, I see error message in console that required "Accept" parameter is not set.

If I put this parameter on operation level, then I see it on UI, but when click "Execute" button it does not send request to server and does not show anything in response, errors or console.

If I remove this parameter completely, then Swagger UI starts work as expected.

But I can't remove it, because Azure/Autorest client does not send 'accept' headers with appropriate mime type without the parameter and I have to keep it in schema to make autorest generated clients work. 

This is on v3.0.3 of Swagger UI, on previous version (2.2.10) it works correctly in all cases

**Comment by webron** [comment]
You shouldn't specify `Accept` as a header parameter. That's why `consumes` exists and that's how you should specify it. Autorest respects `consumes` as well as far as I know so it shouldn't be a problem.

**Comment by xplicit** [comment]
Autorest does not send "Accept" header without explicity adding it in parameters. There is unresolved issue about it https://github.com/Azure/autorest/issues/656

So currently there is no way to use Autorest both with Swagger UI v3, that's why I open this issue.

**Comment by webron** [comment]
That's an issue for Autorest to resolve then, as they don't follow the spec.

**Comment by xplicit** [comment]
By the way, I did not see in specs anywhere that if you define "Accept" header parameter that client must stop work as Swagger UI 3 does.

Moreover Swagger UI 3 does not work with any header parameter, defined at path level, not only `Accept`

**Comment by xplicit** [comment]
```json

"parameters" :
[{
"name":"X-Test",
"in":"header",
"description":"Test Header",
"type":"string",
"required":true,
"enum":["application/json"]
}]
```
is defined at path level. If click "execute" button, I've got error message in console: "Required parameter X-Test is not provided"

**Comment by webron** [comment]
The issue with path level parameters has been resolved - https://github.com/swagger-api/swagger-js/pull/972. Which version of swagger-ui do you test with? Do you experience that the parameter is not rendered but is still required?

If so, it'd help to get a full spec reproducing the issue.

I understand the spec might not be very clear about the `Accept` header, and I'll open a ticket about it, but the issue is still with Autorest.

**Comment by xplicit** [comment]
If define "X-Test" parameter at operation level Swagger UI 3 does not send requests to server, when click "Execute" button.

Swagger UI 2.2.10 does this job correctly both at operation and path level.

**Comment by xplicit** [comment]
At path level "X-Test" does not show in UI, at operation level it shows in UI, but still not work. 
I use the version from master, commit 822dda8

**Comment by webron** [comment]
Yup, I see it now.

**Comment by webron** [comment]
Parameters should be displayed now. Please reopen otherwise.
