### ISSUE TITLE
using this param causes render error 

### ISSUE THREAD

**Issue by supsup** [swagger-api/swagger-ui#3033]
v3.0.8 

`
"parameters": [
{
    "name": "parts",
    "in": "query",
    "required": true,
    "description": "Parts to retrieve",
    "type": "array",
    "items": {
        "type": "string"
    },
    "enum": [
        "A",
        "B",
        "C",
        "D",
        "E",
        "F"
    ],
    "collectionFormat": "multi"
}
]
`
_Is this just invalid syntax?_ 
when you click "Try It Now"

it renders that field as:  '**Could not render this component, see the console**.'
Console has:
`TypeError: p.count is not a function
    at t.value (swagger-ui-bundle.js:95945)
    at t.n.render (swagger-ui-bundle.js:38091)
    at p._renderValidatedComponentWithoutOwnerOrContext (swagger-ui-bundle.js:50643)
    at p._renderValidatedComponent (swagger-ui-bundle.js:50643)
    at performInitialMount (swagger-ui-bundle.js:50643)
    at p.mountComponent (swagger-ui-bundle.js:50643)
    at Object.mountComponent (swagger-ui-bundle.js:44096)
    at performInitialMount (swagger-ui-bundle.js:50643)
    at p.mountComponent (swagger-ui-bundle.js:50643)
    at Object.mountComponent (swagger-ui-bundle.js:44096)`

**Comment by hkosova** [comment]
The `enum` should be on the `items` level, not on the array level.

```
  "parameters": [
    {
      "name": "parts",
      "in": "query",
      "required": true,
      "description": "Parts to retrieve",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "A",
          "B",
          "C",
          "D",
          "E",
          "F"
        ]
      },
      "collectionFormat": "multi"
    }
  ]
```

That said, the UI should probably handle this more gracefully.

**Comment by webron** [comment]
Pretty much what @hkosova said.

**Comment by MRMTC** [comment]
Hi Guys,

I'm having a similar issue.  I have validated my JSON using JSONLint (https://jsonlint.com/), but when I try executing I get the "😱 Could not render this component, see the console." error.  Checking the console, I get the output in the following file:
[editor.swagger.io-1499424919913.txt](https://github.com/swagger-api/swagger-ui/files/1130768/editor.swagger.io-1499424919913.txt)

My input JSON is as in the attached file:
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/1130771/swagger.txt)

Can you please advise on what the issue could be?

Thanks in advance for the assistance.

**Comment by webron** [comment]
@MRMTC there's nothing to test, it uses a fictional host.

Closing the ticket as there's nothing more to add.

**Comment by MRMTC** [comment]
Thanks @webron, so it can't render the output to the page because the host is unreachable?  Is that correct?

Apologies if the above is a silly question - I thought it "mocked" the output.

Thanks.

**Comment by jerrywangatoracle** [comment]
@webron  ：
i just met the same error("Could not render this component, see the console. ")  when i want to execute "try it out"  , Can you help to point me two question : 
1 ） where to find the console of swagger ? can you point me from the pic
![where_is_swagger_console](https://user-images.githubusercontent.com/27404869/28004869-ef17af0e-6579-11e7-9766-394bfd4eea14.jpg)
2 )  when i execute "try it out" after i define the host , the schema(https or http) and the real path, can i get the actual result from swagger-editor just like running on the postman or other restapi client ?

**Comment by MRMTC** [comment]
Hi @jerrywangatoracle,

The "console" refers to the 'Browser Console' where you are executing your tests.   So if you right click on the page, and select "Inspect"; you will be able to choose the console from one of the view.  By using the console, you will be able to debug what is happening on your end.

I believe on your second point, that you are correct.  I'm sure @webron, will be able to confirm.

My issue at the moment is that I don't get that "curl" command showing, hence my original post.

Thanks.

**Comment by jerrywangatoracle** [comment]
@MRMTC   
i just compared the result , the direction of error "Could not render this component, see the console."was just shown where the "curl" command should be showing. hence maybe we were meting the same error.
you can check the screenshot as below
![render error](https://user-images.githubusercontent.com/27404869/28007276-618b6692-6585-11e7-8b49-01921a5d1986.jpg)

**Comment by MRMTC** [comment]
I see, thanks for the confirmation @jerrywangatoracle.  @webron, can you perhaps please provide some clarity for us on the above?

Thanks.

**Comment by webron** [comment]
@MRMTC can you try again with the latest editor?

**Comment by MRMTC** [comment]
Hi @webron,

Thanks so much for getting back to us.  When  I tried now using the "http://editor.swagger.io/#/" link, I got the correct output :)

Thanks again for the assistance!

**Comment by jerrywangatoracle** [comment]
@webron  hi, thanks for your quick response. did you merge the latest modify into the code hence we can download ?

**Comment by webron** [comment]
@jerrywangatoracle it should work now.

**Comment by jerrywangatoracle** [comment]
@webron   
1) opening "http://editor.swagger.io/#/"  with chrome 59.0.3071.109,  the issue still exists.
2) opening "http://editor.swagger.io/#/"  with ie 11, no such issue.

**Comment by webron** [comment]
@jerrywangatoracle would need your API definition to reproduce it.

**Comment by jerrywangatoracle** [comment]
@webron  
 sorry, this issue was only reproduced on the local swagger-editor (i download from https://github.com/swagger-api/swagger-editor.git ), can you help to merge the latest  update to swagger-editor?   From now, it shows "Latest commit 0a9966f  4 days ago" .

**Comment by jerrywangatoracle** [comment]
@webron  
  i raised a issue   https://github.com/swagger-api/swagger-editor/issues/1398 ,  the error "Could not render this component, see the console. " was only existing on my local swagger-editor site .
    BTW,  i need to execute "try it out " with my private host (10.10.*.*) ,  hence i need my private swagger-editor site.

**Comment by ksac1** [comment]
I see the same issue. Still don't know what the solution is. Please clarify.

**Comment by ksac1** [comment]
The solution to the problem : "😱 Could not render this component, see the console." in Swagger Open API 3 can be resolved by following the link: https://swagger.io/docs/specification/describing-parameters/
