### ISSUE TITLE
Collapse / Expand not working correctly for some headers

### ISSUE THREAD

**Issue by 1Map** [swagger-api/swagger-ui#3082]
Another irritating bug I found was the following, regarding collapsing/expanding sections:

Taking the following div example from the UI, the expand/collapse only works on all children within the `<h4 class="opblock-tag">` html tag, and not on the `<h4 class="opblock-tag">` itself. So, you have to click almost dead center inside the h4.

```html
<div class="opblock-tag-section">
	<h4 class="opblock-tag">
		<span>auth</span>
		<small>Authorization Section</small>
		<button class="expand-operation" title="Expand operation">
			<svg class="arrow" width="20" height="20">
				<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#large-arrow"></use>
			</svg>
		</button>
	</h4>
	<noscript></noscript>
</div>
```

## UPDATE: 
I actually found out that the click does work on the h4, but not on the padded area around the h4. You have to click in the center of the h4. If you click on the padded area around the h4 then click does not work. Strange is, it does work correctly on the Models header, although that also has a padded area around its h4.

**THE NON-WORKING ONE:**

image
![image](https://cloud.githubusercontent.com/assets/1152458/26056673/a2768546-3976-11e7-81bc-3abd12a9b91a.png)

**THE WORKING ONE:**

image
![image](https://cloud.githubusercontent.com/assets/1152458/26056680/a8c9b418-3976-11e7-896e-4b928ccc15a7.png)

**Comment by 1Map** [comment]
Any update on this issue?

**Comment by shockey** [comment]
Fixed via #3116!

**Comment by 1Map** [comment]
@shockey Please do not just close issues if it was not tested properly by the author of this ticket.  This issue is not fixed (Well, not in the latest dist).  Please reopen and test properly.

**Comment by webron** [comment]
It doesn't work in the live demo because we deploy it every weekend after we release a version (normally on Fridays).

*Despite* your attitude, I will reopen the ticket. However, we will not spend additional time fixing this issue as it's an extremely low priority in my view. If you'd like to submit a PR to fix it because it bothers you, we'd love to review and merge it.

**Comment by 1Map** [comment]
Thank you,

And remember in the future, test, test, test before closing a ticket.  We are here to help.  Rather ask the person who opened the ticket to also test (as I did).

**Comment by shockey** [comment]
Jumping in... I tested prior to merging the PR, as I do with every PR. It is fixed in the source, I just checked again to be sure. Generally, we optimistically close tickets when it appears to be fixed, and allow for further discussion and reopens if there are ongoing problems.

You're correct, though - it's not fixed in dist - as dist isn't stable or predictable between releases. If you'd like to see keeping dist in sync become a standard practice, consider chiming in on https://github.com/swagger-api/swagger-ui/issues/3014. Beyond that, you can build your own dist folder by cloning the repository and running `npm run build` if you'd like.

As Ron mentioned, the demo is updated when we release on Friday afternoons, same with the `dist` folder. I'll be running a release in a few hours, so you'll be able to catch the fix in master's dist files then.

I've deployed a version of the latest master to Surge, you can check it now to confirm that it's fixed: handy-legs.surge.sh

**Comment by 1Map** [comment]
Thanks @shockey 

Yes, sorry about that.  Thought when I saw that the ticket was closed that it was already in the dist.

**Comment by shockey** [comment]
Yeah, I see that a couple of dist files were updated - looks like just the core files. That would be an artifact from our dev server, not a full build, which would generate 8 files.

It seems to me that this is stemming from a lack of expectations on what "closed" means. I'll try to be more explicit about release strategy in my closing messages.

Also, FYI: I should have the new UI release done in a few minutes.

**Comment by webron** [comment]
@1Map have you had a chance to test it?

**Comment by 1Map** [comment]
@webron Thanks, it is now working 100% - Appreciate - You can close this ticket.
