### ISSUE TITLE
multipart/form-data parameters sent as "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by kwieconkowski** [swagger-api/swagger-ui#3375]
Hello,
I'm using swagger to generate jax-rs documentation with swagger-jaxrs and it`s working fine. The problem is with swagger-ui (3.0.18, from: https://github.com/swagger-api/swagger-ui/archive/master.tar.gz). The simplest example, we have POST method with one 'formData' parameter. This is send as 'application/x-www-form-urlencoded', not as required 'multipart/form-data'. Walkaround is inserting an additional parameter of type 'file', that will make the request as 'multipart/form-data' (correct). If this helps, there was the same issue some time ago and fixed (https://github.com/swagger-api/swagger-ui/issues/1938).

Example:
```json
{  
   "swagger":"2.0",
   "info":{  
      "title":"someTitle",
      "version":"1.0.2"
   },
   "host":"localhost:8080",
   "basePath":"/rest",
   "tags":[  
      {  
         "name":"someName"
      }
   ],
   "schemes":[  
      "http"
   ],
   "paths":{  
      "/upload/fromDB":{  
         "post":{  
            "tags":[  
               "someName"
            ],
            "summary":"someSummary",
            "description":"someDescription",
            "operationId":"storeFromDB",
            "consumes":[  
               "multipart/form-data"
            ],
            "produces":[  
               "application/json",
               "application/xml"
            ],
            "parameters":[  
               {  
                  "name":"parmName",
                  "in":"formData",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{  
               "200":{  
                  "description":"Number of stored documents",
                  "schema":{  
                     "type":"integer",
                     "format":"int32"
                  }
               }
            }
         }
      }
   },
   "definitions":{ }
}
```

**Comment by webron** [comment]
@owenconti can you take a look at this one please? It's possible this is coming from swagger-js.

**Comment by shockey** [comment]
This should be fixed in `master`! We'll release a new version tomorrow evening with this fix in it.

Thanks for reporting this, @kwieconkowski!

**Comment by kwieconkowski** [comment]
@owenconti @shockey I have tested today using newest distribution and still doesn`t work as supposed. Content-type is 'application/x-www-form-urlencoded' instead of 'multipart':

```
curl -X POST "http://localhost:8080/rest/upload/someMethod" -H "accept: application/json" -H "content-type: application/x-www-form-urlencoded" -d "someParam=example"
```
For swagger document:
```yaml
swagger: "2.0"
info:
  version: "1.0.2"
host: "localhost:8080"
basePath: "/rest"
tags:
- name: "someTag"
schemes:
- "http"
paths:
  /upload/someMethod:
    post:
      tags:
      - "someTag"
      summary: "someSummary"
      description: "someDescription"
      operationId: "uniqueId"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "someParam"
        in: "formData"
        required: false
        type: "string"
      responses:
        200:
          description: "Number of stored documents"
          schema:
            type: "integer"
            format: "int32"
definitions:
```
