### ISSUE TITLE
Selecting "https" scheme doesn't change curl command

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-ui#3470]
I have "http" and "https" schemes enabled in my swagger spec.
Selecting "https" does not change the curl commands output when executing methods in the Swagger UI.

Unfortunately, I cannot attach swagger spec (proprietary).
I am using the latest swagger-ui from master (I copied the "dist" files into my web server and just edited the path to the Swagger spec in index.html).

**Comment by webron** [comment]
You don't have to provide your own spec, but please provide a minimal one that reproduces the issue.

**Comment by tanatana** [comment]
Hi, I'm in experience same issue.

Following is minimal spec that reproduces the issue.

```yml
swagger: "2.0"
info:
  description: "scheme selector test"
  version: "1.0.0"
  title: "Scheme selector test"
host: "cors-test.appspot.com"
schemes:
- "http"
- "https"
paths:
  /test:
    get:
      summary: "test"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
      schemes:
      - "http"
      - "https"
```

**Comment by shockey** [comment]
This should be fixed in `master` now 🎉

**Comment by delenius** [comment]
I still see the same problem. Were the files in `dist` updated?

**Comment by shockey** [comment]
@delenius, they weren't (we only update them during release). They'll be updated tomorrow evening as part of our weekly Friday release 😄
