### ISSUE TITLE
$$ref appears in referenced JSON file for example

### ISSUE THREAD

**Issue by donaldpipowitch** [swagger-api/swagger-ui#3638]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | v3
| Which Swagger-UI version?       | v3.1.7
| How did you install Swagger-UI? | `$ npm i swagger-ui-dist`
| Which browser & version?        | Chrome 60
| Which operating system?         |  Mac

### Demonstration API definition

```yaml
openapi: 3.0.0
info:
  title: Example API
  version: 1-draft

paths:
  /:
    get:
      summary: Returns foo.
      responses:
        200:
          description: |-
            The foo object.
          examples:
            application/json:
              $ref: "examples/root.json"
```

```json
{
  "foo": "bar"
}
```

### Expected Behavior

Swagger UI renders my example as:

```json
{
  "foo": "bar"
}
```

### Current Behavior

Swagger UI renders my example as:

```json
{
  "foo": "bar",
  "$$ref": "examples/root.json"
}
```

![image](https://user-images.githubusercontent.com/1152805/30112737-a6c856b0-9312-11e7-8ae8-3abcda42bef0.png)

---

Note: If I use a `.yaml` instead like this:

```yaml
Example: |-
  {
    "foo": "bar"
  }
```

And write `$ref: "examples/root.yaml#/Example"` the example renders correctly.

**Comment by shockey** [comment]
Fixed.

Thanks for the report, @donaldpipowitch!

**Comment by donaldpipowitch** [comment]
Thank you for the fix.

**Comment by dmolesUC3** [comment]
I'm still seeing this in 3.4.3:

![screen shot 2017-11-07 at 12 43 02 pm](https://user-images.githubusercontent.com/10374934/32516753-457da5cc-c3b9-11e7-999a-0b94c3981713.png)

You can see this by pasting `https://github.com/dmolesUC3/stash_api/blob/153b5a25b95436df7c76ba0280ae762e3dfc337e/public/openapi.yml` into the [petstore.swagger.io](http://petstore.swagger.io) Explore bar. Is there something wrong with my syntax?

```
components:
  schemas:
    root:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/hal_links'
      required:
        - _links
      example:
        $ref: examples/root.json
```

**Comment by webron** [comment]
According to the spec, Schema Object's `example` does not support a reference value. You'd have to add the example inline for it to work.

**Comment by dmolesUC3** [comment]
I believe you, but can you explain what's going on in the first example of [this section of the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#examplesObject)?

> #### Examples Object
>
> In an `example`, a JSON Reference MAY be used, with the explicit restriction...
>
> ```
> # in a model
> schemas:
>   properties:
>     name:
>       type: string
>       example:
>         $ref: http://foo.bar#/examples/name-example
> ```

**Comment by dmolesUC3** [comment]
It looks like "Examples Object", plural, has been removed from the [3.0.1 spec](https://github.com/OAI/OpenAPI-Specification/blob/v3.0.1/versions/3.0.1.md), so maybe that section was in error.

**Comment by webron** [comment]
The `Examples Object` was a left over in 3.0.0 - but it's not referenced anywhere inside the specification so it's not really relevant. If you look at the Schema Object, at the example field itself, that's what matters.
