### ISSUE TITLE
Enum values not displayed in models

### ISSUE THREAD

**Issue by sosoxuc** [swagger-api/swagger-ui#672]
I think not showing available values in model makes  API unclear.

**Comment by eloleon** [comment]
Hi all, I'm getting same issue. It would be great if option for defining available values by using enums would be available. webron said that I should create issue here but there is one already ( http://stackoverflow.com/questions/27603871/how-to-define-enum-in-swagger-io ). 
Do you think it will be solved anytime soon?

**Comment by webron** [comment]
Well, don't blame me. I don't remember *all* opened issues ;)

**Comment by eloleon** [comment]
It was my bad, I should check issue list here before posting question. Thanks for all you suggestions

**Comment by webron** [comment]
No worries, it's not easy finding all available information.

**Comment by tshah010** [comment]
Hi, has this issue been fixed? If yes, which version is it available in? Thanks.

**Comment by fehguy** [comment]
Please note that it's targeted for 2.1.0-M2

**Comment by nicolastrres** [comment]
Hi all I am getting the same issue. Is this fixed?

**Comment by webron** [comment]
@nicolastrres - should be fixed. If not in master then in develop_2.0.

**Comment by hiveship** [comment]
I'm still facing the problem with the current master branch. 
I've reported it in issue 2184

**Comment by SonnyRajagopalan** [comment]
Still have this issue (enums in *.yaml not displaying in UI). Is it going to be fixed soon?

**Comment by webron** [comment]
@SonnyRajagopalan there shouldn't be an issue with the latest master. If you encounter an issue, open a new ticket and provide a full spec that reproduces the problem.

**Comment by SonnyRajagopalan** [comment]
@webron , My profound apologies. Tooling error on my part (dealing with an obscenely large spec so I have tools that generate metadata that generate more metadata which finally generate yaml code...). It works just fine. Thanks a heap for your quick response!

**Comment by liteultom** [comment]
Had the same problem, it would appear that an enum without a "type" specified is not displayed in swagger UI. Adding the "type" to the field definition was enough for it to work.
