### ISSUE TITLE
client_credentials and authorization_code cannot be used simultaneously

### ISSUE THREAD

**Issue by rwb196884** [swagger-api/swagger-ui#8199]
In `UseSwaggerUI`  calling `OAuthUsePkce` makes the `client_secret` textbox disappear for all flows. It is therefore impossible to use client_credentials (which requires a client_secret) and authorization_code (which requires this field to be absent) at the same time.

**Comment by shamnani-kamlesh** [comment]
We have same issue. seems its fixed here - https://github.com/swagger-api/swagger-ui/pull/8146

**Comment by rwb196884** [comment]
This does indeed appear to be fixed in version 6.4.0.

The following setup
```
    OpenApiOAuthFlow flowAC = new OpenApiOAuthFlow()
    {
        AuthorizationUrl = new Uri($"{jwtBearerOptions.Authority}/connect/authorize"),
        TokenUrl = new Uri($"{jwtBearerOptions.Authority}/connect/token"),
        Scopes = new Dictionary<string, string>() { 
            { AuthorizationPolicy.TruthPortal, "Truth portal web" },
            {"profile", "profile" },
            {"openid", "openid" },
            {"offline_access", "offline_access" }
        },
    };

    OpenApiOAuthFlow flowCC = new OpenApiOAuthFlow()
    {
        AuthorizationUrl = new Uri($"{jwtBearerOptions.Authority}/connect/authorize"),
        TokenUrl = new Uri($"{jwtBearerOptions.Authority}/connect/token"),
        Scopes = new Dictionary<string, string>() { { AuthorizationPolicy.Integration, "Truth integrations" } }
    };

    c.AddSecurityDefinition(Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, new OpenApiSecurityScheme()
    {
        Description = "Bearer token",
        In = ParameterLocation.Header,
        Name = "Authorization",
        Scheme = "Bearer",
        BearerFormat = "JWT",
        Type = SecuritySchemeType.OAuth2,
        Flows = new OpenApiOAuthFlows()
        {
            ClientCredentials = flowCC,
            AuthorizationCode = flowAC
        }
    });

    // Adds the token to requests.
    c.AddSecurityRequirement(new OpenApiSecurityRequirement()
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme
                },
                Scheme = "Bearer", // https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
                In = ParameterLocation.Header
            },

            new List<string>()
        }
    });
```
Renders this sort of thing:
![image](https://user-images.githubusercontent.com/12090617/210351084-d78e71f9-0844-4c9b-b885-cdfe0d536f2d.png)

**Comment by rwb196884** [comment]
No. It's still broken.

Authorization coede flow requires PKCE but if you
```
    app.UseSwaggerUI(c =>
    {
        c.OAuthUsePkce(); // bug: determines wither client_secret field is either present or absent for all flows.
    });
```

then the `client_secret` field disappears from _both_ cases. Thereore at least one case cannot work.

FFS.
