### ISSUE TITLE
UI crashes on complex OpenAPI documents

### ISSUE THREAD

**Issue by pavelkornev** [swagger-api/swagger-ui#9513]
### Q&A (please complete the following information)
 - OS: macOS, Windows
 - Browser: Chrome
 - Version: 120.0.6099.234
 - Method of installation: web version - https://editor-next.swagger.io/
 - Swagger-UI version: n/a
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

When rendering a complex OpenAPI document, UI comes unresponsive first with the following browser dialog, and eventually crashes later:
![swagger-ui-1](https://github.com/swagger-api/swagger-ui/assets/748043/ff792adc-550c-4900-8cd3-c983cd72ccda)
![swagger-ui-0](https://github.com/swagger-api/swagger-ui/assets/748043/9cee725a-9513-4723-9102-197a2088c8ab)
![swagger-ui-2](https://github.com/swagger-api/swagger-ui/assets/748043/8574471b-69ff-4f8c-a903-ee012a3fd34a)

Example Swagger/OpenAPI definition:
https://api.sap.com/odata/1.0/catalog.svc/APIContent.APIs('SAP_ICSM_StudyService')/$value?type=json

### To reproduce...

1. Go to https://editor-next.swagger.io/
2. Paste content from this link: https://api.sap.com/odata/1.0/catalog.svc/APIContent.APIs('SAP_ICSM_StudyService')/$value?type=json
3. Try to expand first operation "/BlindingGroups"

### Expected behavior
UI doesn't crash.

**Comment by Coder-Manuel** [comment]
Am also experiencing the same, Any fix/walk-around ?

**Comment by glowcloud** [comment]
Investigating this issue within Swagger Client, I found out that the resolve mechanism executes for a long time due to the complexity of the specification with the nested references. The specification should eventually be resolved but the operations take too long. Because of this SwaggerUI will freeze. 

I tried breaking out of the traversal early by creating and setting a maximum count of it to a 1000 for each run of the plugins. I broke out of the execution here https://github.com/swagger-api/swagger-js/blob/f00b527fd71f46ccf1a4ae14853edc5452160b04/src/specmap/index.js#L108 and here https://github.com/swagger-api/swagger-js/blob/f00b527fd71f46ccf1a4ae14853edc5452160b04/src/specmap/index.js#L137 if the limit was reached. This allowed the specification to be partially resolved and loaded in SwaggerUI, although rendering slowly. Unfortunately, as we don’t resolve everything, components looked like this: 

<img width="660" alt="ex_path" src="https://github.com/swagger-api/swagger-ui/assets/44094416/30f8847d-c2ea-420d-b608-9452302ff84c">

<img width="580" alt="ex_component" src="https://github.com/swagger-api/swagger-ui/assets/44094416/789dfbd5-bf49-4164-bd95-ffc4bbcd2f27">

The missing values are unresolved, for example `scenario` from the second image is:  
```
{
  allOf: [
    {
      '$ref': '#/components/schemas/com.sap.ctsm.backend.core.api.study.v1.StudyAPIv1.Scenarios-create'
    }
  ],
  nullable: true
}
```
and `kitTypeAssignments`: 
```
{
    type: 'array',
    items: {
      '$ref': '#/components/schemas/com.sap.ctsm.backend.core.api.study.v1.StudyAPIv1.KitTypeTreatmentAssignments-create'
    }
  }
```

Perhaps we could render these unresolved definitions with reference strings but resolving everything is not possible at the moment.

**Comment by glowcloud** [comment]
The crashing issue was addressed in https://github.com/swagger-api/swagger-js/pull/3380, released as https://github.com/swagger-api/swagger-js/releases/tag/v3.25.3. 

As it turned out, the complex specification was being eventually resolved, but the operations took too long due to the nested definitions. To fix this, we limited the maximum traversal depth for each run of the plugins. This allows us to get a partially resolved specification, which has to be resolved further in Swagger UI. 
A fix was also added for the limit of the plugins dispatch runs, which now correctly tracks each plugin separately.

**Comment by glowcloud** [comment]
Rendering schemas not resolved by Swagger Client addressed in https://github.com/swagger-api/swagger-ui/pull/9629.

**Comment by pavelkornev** [comment]
This still fails on the original example given in the issue description.

**Steps:**
1. Go to https://editor-next.swagger.io/
2. Paste content from this link: https://api.sap.com/odata/1.0/catalog.svc/APIContent.APIs('SAP_ICSM_StudyService')/$value?type=json
3. Expand first operation "/BlindingGroups"
4. Collapse the expanded operation "/BlindingGroups"
5. Expand second operation "/BlindingGroups({ID})" -> **crash!**

**Comment by char0n** [comment]
I've did additional measurements about Immutable.js serialization speed and memory footprint on this definition:

### Using pure JavaScript (without Immutable.js):

**Memory consumption:**

```
Before: 88,788,992 bytes (approximately 88.79 MB)
After: 155,521,024 bytes (approximately 155.52 MB)
Change: Increased by 66.73 MB
```

**Serialization time:**

```
0 ms
```

### Using Immutable.js:

**Memory consumption:**

```
Before: 90,148,864 bytes (approximately 90.15 MB)
After: 1,044,697,088 bytes (approximately 1.04 GB)
Change: Increased by approximately 954.55 MB
```

**Serialization time:**

```
3163 ms
```

**Comment by pavelkornev** [comment]
@char0n would you consider dropping Immutable.js if it causes such a big memory consumption?

**Comment by char0n** [comment]
> @char0n would you consider dropping Immutable.js if it causes such a big memory consumption?

Yes it's a long term plan. But it basically means rewriting the entire SwaggerUI. SwaggerUI basically consists of selectors, reducers, actions and components and Immutable.js is the interface that all of these bind to.  

After we've removed Immutable.js we still have problem of dereferencing lasting 25 seconds on your definition. We can solve that by hard stopping the dereferencing at certain level. 

Then the next issue is probably going to be example generation from JSON Schemas. Given the extreme schema complexity, this problem can be totally avoided by defining one of the JSON Schema keywords: `default`, `example`, `examples` in all your JSON Schemas.

**Comment by Liamhhhhh** [comment]
In this case, you can try generating documents in [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1), which may solve your problem.

**Comment by momala454** [comment]
I have a json swagger that is 3.5 mb large.
When configured with openapi 3.0.0, expanding an endpoint is instantaneous, but if i change the version to 3.1.0, expanding can take like 6 seconds, and the initial load of the page also takes 5 seconds with 3.1, and completely instantaneous with 3.0.0.

How can I improve it ?
