### ISSUE TITLE
Swagger UI not able to handle URI's with the @ symbol

### ISSUE THREAD

**Issue by banichols** [swagger-api/swagger-ui#956]
I'm working on a JAX-RS suite with endpoints that have an @ symbol in their URI. It appears that swagger is able to generate valid JSON to represent these endpoints, but swagger-ui fails when attempting to read them. 

Example swagger JSON output that fails in swagger-ui:

```
http://localhost:8585/v1/api/api-docs/people/@me
{
    "apiVersion": "1.0.0",
    "swaggerVersion": "1.2",
    "basePath": "http://localhost:8585/v1/api",
    "resourcePath": "/people/@me",
    "produces": [
        "application/xml",
        "application/json"
    ],
    "consumes": [
        "application/xml",
        "application/json"
    ],
    "apis": [
        {
            "path": "/people/@me/profile",
            "operations": [
                {
                    "method": "GET",
                    "summary": "Get profile for a person.",
                    "type": "void",
                    "nickname": "getSlimProfile",
                    "produces": [
                        "application/xml",
                        "application/json"
                    ],
                    "parameters": [
                        {
                            "name": "X-Person-ID",
                            "required": false,
                            "type": "integer",
                            "format": "int64",
                            "paramType": "header",
                            "allowMultiple": false
                        }
                    ]
                }
            ]
        }
    ]
}
```

The error displayed in the UI is: ``` "Unable to read api '@me' from path http://localhost:8585/v1/api/api-docs/people/@me (server returned undefined)" ```

Note: Swagger-UI works for my suite as long as any endpoints with an @ sign are left out of the generated swagger JSON.

**Comment by fehguy** [comment]
Hi, can you please show a screenshot of the network panel?

**Comment by banichols** [comment]
From Chrome's javascript panel: 

![swagger-ui-error](https://cloud.githubusercontent.com/assets/6365175/6378284/2cdcff92-bcdf-11e4-9408-8cedfbc74633.png)

Note that I am running swagger-ui 2.0.24

**Comment by fehguy** [comment]
This has been fixed in swagger-ui 2.1.x-M1. Can you please upgrade and report back?

**Comment by banichols** [comment]
I pulled the latest from master, and am still seeing the same behavior:

![swagger-ui-2 1 x-m1-error](https://cloud.githubusercontent.com/assets/6365175/6379165/26e10e7a-bce5-11e4-800c-1ea4941867ac.png)

**Comment by fehguy** [comment]
Hi, you are correct, it is actually not fixed for paths.  It _is_ fixed for parameters though.

The underlying issue is in the `parseUri` function that is being used in the underlying `shred` library.  Until that is fixed (it's the world's ugliest [regex](https://github.com/swagger-api/swagger-js/blob/master/lib/shred.bundle.js#L1332-L1333) ), you can work around it by using jQuery when initializing swagger ui:

```
window.swaggerUi = new SwaggerUi({
  url: url,
  useJQuery: true,
```

**Comment by banichols** [comment]
I've confirmed that the "useJQuery: true" workaround does remedy the issue

**Comment by mohsen1** [comment]
It's a bug in SwaggerJS. https://github.com/swagger-api/swagger-js/issues/267. Please look for resolution there.
